name: auth_practice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  google_fonts: ^6.2.1
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  snackbar: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
